# Generated by Django 2.2.5 on 2019-09-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20190925_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='panel_provider_id',
            new_name='panel_provider',
        ),
        migrations.RenameField(
            model_name='locationgroup',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='locationgroup',
            old_name='panel_provider_id',
            new_name='panel_provider',
        ),
        migrations.RenameField(
            model_name='targetgroup',
            old_name='panel_provider_id',
            new_name='panel_provider',
        ),
        migrations.RenameField(
            model_name='targetgroup',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RemoveField(
            model_name='location',
            name='external_id',
        ),
        migrations.AddField(
            model_name='location',
            name='external',
            field=models.IntegerField(default=None),
        ),
    ]
