# Generated by Django 2.2.5 on 2019-09-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_auto_20190925_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='panel_size',
            field=models.IntegerField(default=0),
        ),
    ]
