# Generated by Django 2.2.5 on 2019-09-25 17:24

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panel_provider_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='secret_code',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='secret_code',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
