# Generated by Django 2.2.5 on 2019-09-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_provider_pricing', '0003_auto_20190925_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='external',
            new_name='external_id',
        ),
    ]
