# Generated by Django 2.2.5 on 2019-09-25 20:50

from django.db import migrations

from .tasks import seed_the_database


class Migration(migrations.Migration):
    dependencies = [
        ("panel_provider_pricing", "0004_auto_20190925_2005"),
    ]

    operations = [
        migrations.RunPython(seed_the_database.execute),
    ]
